server:
  port: ${APP_SERVER_PORT:8081}

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true

telegram:
  bot-name: ${TELEGRAM_BOT_NAME}
  bot-id: ${TELEGRAM_BOT_ID}
  bot-token: ${TELEGRAM_BOT_TOKEN}

application:
  posting-delay: ${POSTING_DELAY:60000}

logging:
  file:
    name: ./logs/tmps.log
