# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@bd5760595778326ba7f1441bcf7e88b49de61a25 # v2.6.0
      with:
        arguments: build

    - name: Upload application
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        source: "TMPS.jar"
        target: "~/source"

    - name: Start Service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP_ADDRESS }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: 22
        script: |
          sudo /etc/init.d/TMPS stop
          mv ~/source/TMPS.jar ~/source/TMPS-old.jar
          mv ~/source/TMPS-latest.jar ~/source/TMPS.jar
          sudo rm -rf /etc/init.d/TMPS
          sudo ln -s -f ~/source/TMPS.jar /etc/init.d/TMPS
          sudo /etc/init.d/TMPS start
          rm ~/source/TMPS-old.jar